### ISSUE TITLE
NusKeys assembly missing 

### ISSUE THREAD

**Issue by Freeben666** [zedseven/NusRipper#1]
Hello,

I wanted to try out this software, but apparently part of the code is missing.? The project file reference's a NusKeys.dll which is missing. I understand that for legal reasons you may not be able to share the DLL as-is. But could you include the code, without any copyrighted material ? I'm sure I could figure out something from there ;)

Best regards

**Comment by zedseven** [comment]
Hi,

As you said I cannot share the DLL - I've just updated the README with more information (truth be told I should have done that upon project completion, but I forgot). You can find a pre-compiled build (that does not include the DLL) under the Releases tab.

Thanks for taking interest in the project! I am planning on making a more user-friendly general-use tool for things like this at some point, but I don't have a timeline for when that will be.

Have a wonderful day,
Zacc

**Comment by Freeben666** [comment]
Thanks for the answer. I coded my own NusKeys assembly and all works well ;)
